services:
  tfn-server-dev:
    image: nwnxee/unified:2f732e7
    platform: linux/x86_64
    tty: true
    stdin_open: true
    env_file: ${PWD-.}/config/common.env
    environment:
    - NWN_PUBLICSERVER=0
    - NWN_SERVERNAME="The Frozen North DEV"
    - NWN_PORT=5134
    - NWNX_SERVERLOGREDIRECTOR_LOG_LEVEL=6
    - NWNX_PROFILER_SKIP=y
    - NWNX_METRICS_INFLUXDB_SKIP=y
    - NWN_DMPASSWORD=tfndev
    ports:
    - '5134:5134/udp'
    volumes:
    - ${PWD-.}/logs:/nwn/run/logs.0
    - ${PWD-.}/:/nwn/home
